# Generated by Django 4.2.6 on 2023-10-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_teatcher_name_student_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='student',
            name='first_semester_grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='second_semester_grade',
            field=models.FloatField(default=0),
        ),
    ]
