# Generated by Django 4.2.6 on 2023-10-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_age_student_first_semester_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_semester_grade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_semester_grade',
            field=models.FloatField(),
        ),
    ]
